README.md
git clone git@... will not work for most users who don't have privileged ssh keys. I'm sure this won't confuse most uses but I thought I'd be helpful and point the mistake out.
=> Very minor documentation bug

intero.cabal
`-dynamic` doesn't work on Windows. Intero works quite nicely with this in though!
=> Don't use -dynamic on Windows

src/InteractiveUI.hs
`:completion` command can be used to set `completionMode` for a given macro
```
syntax: :completion <macro> none|expr|file|module|identifier
```
Example:
```haskell
:def which-package \ m -> return $ ":! ghc-pkg --simple-output find-module " ++ m
:completion which-package module
```
=> add configuration completion

elisp/intero.el
Some modes decorate the buffer file name with faces, e.g. flx-ido.
Arguably this is a bug in said modes, but at any rate this simple fix
protects against any potential issues.
In particular, if we don't strip properties, then the `:type-at`
string generated by intero includes garbage and a syntax error ensues.
=> Strip properties from (buffer-file-name).

elisp/intero.el
In defun intero-check, calling write-region will print a message "Wrote
<file>". In my environment, flycheck always happens after doing "C-c
C-t". And the "Wrote <file>" makes the type information in my minibuffer
gone in one second or so. This is really annoying.
=> Don't print "Wrote <file>" message on flycheck

elisp/intero.el
People used to the `interactive-haskell-mode`  REPL loading behaviour (`C-c C-l`) expect the current buffer to be saved before loading.
To demonstrate the current behaviour, define:
```haskell
foo = putStrLn "hey"
```
Save, `C-c C-l` and test the value of foo. The repl will print `hey`.
Now change `foo` to:
```haskell
foo = putStrLn "hi"
```
and without saving, load the repl again with `C-c C-l`. `foo` will still print `hey`.
=> Save current buffer before loading REPL

README.md
I thought it should be great to display the default provided key bindings for Emacs (especially intero-repl-load which is missing in http://commercialhaskell.github.io/intero/).
Thanks for your awesome work!
=> Added default key bindings in readme.

elisp/intero.el
The use case for this is similar to that of haskell-mode's
haskell-doc-mode.  However, this has the advantage of using intero to
retrieve the type information.
=> Implement basic eldoc-mode backend

stack.yaml
In order to fix the intero integration for NixOS, one solution is to modify the `~/.stack/config.yaml` as described in #52, but we need both the *ncurses* package and [nix to be enabled](http://docs.haskellstack.org/en/stable/nix_integration/#additions-to-your-stackyaml):
```yaml
nix:
enable: true
packages: [ ncurses ]
```
Best solution is to add these default options in the `stack/config.yaml` of the project!
=> Added mandatory enable option for NixOS.

elisp/intero.el
=> Pass missing "limit" arg to looking-back invocation

elisp/intero.el
Also use font-lock-ensure when available rather than the now-deprecated font-lock-fontify-buffer.
=> Extract duplicated code for fontifying expressions

elisp/intero.el
I like to set `debug-on-error` so that things fail noisily -- this doesn't mean I want debug output from everything. This commit introduces an `intero-debug` var to specifically control whether `intero` is verbose.
=> Don't misuse debug-on-error to determine verbosity

elisp/intero.el
This fixes the "not in scope" regex to work with GHC8 and sets a typo fix replacement widget to be enabled by default if it is the only suggested fix.
=> Default typo fix

elisp/intero.el
This is a slight augmentation of the existing identifier typo auto-correct.
=> Offer to fix constructor name typos

README.md
As implemented in #197, we have `C-c C-k` to clear the repl now!
=> Add Clear REPL key binding to the README

elisp/intero.el
This fixes most of the issue highlighted in #188 just to avoid leaving bugs dangling.
All further correction application code is on hold until the source parsing is moved into the intero process.
=> Make constraint parsing robust to nested parens

elisp/intero.el
Quickfix already sorts the lines backwards to apply fixes, as they may
change the source location.  This however bearks down if two changes
happen in the same line.  Hence we add the column to the sort criteria
as well, such that corrections in the same line are applied in reverse
as well.
Fixes #202
=> Sort on column as well.

src/Main.hs
This will be used so that stack can interrogate what executable it is running against to know if it should use features available in intero, or just GHCi.
=> Add program identifier to version command flag.

src/InteractiveUI.hs
:unset now has the same behavior that exists in GHCi.
=> Fixed unset of extensions.

elisp/intero.el
This is related to a comment I just left on an older commit; hopefully this adds some clarity.
I don't know why this `cdr` is needed. When intero gives back a single completion, this `cdr` drops it, preventing `company` from showing any completions at all. I may be unaware of the scenario where the `cdr` is needed. If so, apologies for the disturbance!
=> Don't drop the first company completion

elisp/intero.el
@purcell See any problem with this?
``` haskell
Par...   68  28 error           Couldn't match expected type ‘[t0] -> P (a SrcSpanInfo)’
with actual type ‘P (a SrcSpanInfo)’
Relevant bindings include
p :: P (a SrcSpanInfo)
(bound at /var/folders/2s/6j1qqrgd57bg9ctkltrkn3z80000gn/T/intero52962niH.hs:68:22)
normalParserNoFixity :: P (a SrcSpanInfo)
-> Maybe [Fixity] -> P (a SrcSpanInfo)
(bound at /var/folders/2s/6j1qqrgd57bg9ctkltrkn3z80000gn/T/intero52962niH.hs:68:1)
The function ‘p’ is applied to one argument,
but its type ‘P (a SrcSpanInfo)’ has none
In the expression: p []
In an equation for ‘normalParserNoFixity’:
normalParserNoFixity p _ = p []... (intero)
```
=>
``` haskell
Par...   68  28 error           Couldn't match expected type ‘[t0] -> P (a SrcSpanInfo)’
with actual type ‘P (a …
```
=> Replace temp filename with real filename (#248)

elisp/intero.el
Reverts commercialhaskell/intero#249
Not at a keyboard to fix this so I'll revert.
=> Revert "Replace temp filename with real filename (#248)"

elisp/intero.el
Just a couple of things I noticed. Re. the checkdoc issues, flycheck will highlight all of these, and it's worth keeping the docstrings clean IMO.
=> Couple of elisp fixes

elisp/intero.el
I got quite confused by this warning this morning:
```
Warning (emacs): Couldn’t get the Stack project root.
This can be caused by a syntax error in your stack.yaml file. Check that out.
Otherwise, please report this as a bug!
```
Where should I report this bug? Googling the error message found me https://hackage.haskell.org/package/intero-0.1.17/src/elisp/intero.el, which lead me here.
It seems a little odd to suggest that people report a bug without giving them a hint as to where (at the time, I had thought I had disabled intero, because it clearly didn't like me trying to edit a Haskell file that wasn't in a project.)
In any case, this PR updates the warning to say it's from intero, not emacs.
=> Be clear that warnings come from intero

elisp/intero.el
i can not find any reason why we don't display `λ` in prompt but `‽`. i mean in every prompt of a FP language, there will be a `λ`. 😅 
Btw, there is one thing confusing me a lot while walking through the code base, why we need to [a temp file](https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L1048-L1057), and all the infos are coming from the temp file, e.g. [type-at](https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L1111) ?
=> Display λ in prompt

elisp/intero.el
As discussed in https://github.com/commercialhaskell/intero/commit/bb2012df5e42ce657b51cf66d88f069563c7e5d7 .
My level of confidence is low: I have never written lisp code, I simply stumbled upon [a similar issue][1] that says `format-message` should be replaced with `format`. Please double-check.
[1]: https://gitlab.com/python-mode-devs/python-mode/issues/21
=> Replace format-message with format

elisp/intero.el
See #279. When enabling docker for stack, the docker image cannot see /tmp paths on the host system. With this change, .stack-work/intero/ is used as the location for temporary copies of the current working source file.
This commit does not change the containing directory for *all* intero temp files, because it is not clearly necessary to do so, but that might 
be a logical subsequent step for the sake of consistency.
Moving temp files to .stack-work/intero/ potentially allows intero to proactively delete all its temp files upon exit, which would be a win, since the code was previously relying on the OS to tidy up the temp dir.
=> Store temporary working files under .stack-work, not /tmp

elisp/intero.el
This change allows one to fall back to a different lookup if Intero does not know about the symbol. E.g. I use Intero with codex: `(or (intero-goto-definition) (find-tag (find-tag-default)))`
=> Change intero-goto-definition success return value

elisp/intero.el
Intero 0.1.18 misses very important feature which makes inital haskell
experience less then ideal - not really representing the current state of
Intero. Completion of qualified identifiers should be considered essential and
as such It should justify bumping package version to 0.1.19
=> bumping package version to auto-install

elisp/intero.el
This addresses #311, in which .hs was wrongly used unconditionally.
=> Use .lhs for temp files when necessary to match the current buffer

src/GhciInfo.hs
Just simple fix for printed type of constructors
Reported by : https://github.com/commercialhaskell/intero/issues/67
However, there is some problem with existential types. For example,
``` Haskell
data Sh = forall a . Show a => Sh a
test (Sh x) = show x
```
In this case, printed type of `Sh` in piecewise definition of `test` is `a -> Sh`, and is not the correct type, i.e, `forall a . Show a => a -> Sh`.
This problem also can be fixed by collecting more data from `ConPatOut`, but I ran out of time so I make this PR first.
=> Fix type of constructors in pattern

src/GhciInfo.hs
Remove unused import that cause build error under (ghc < 8.0.0).
=> Remove unused import

elisp/intero.el
Wrote functions to expand template haskell splice at point. point needs to be over the template haskell expression being expanded (rather than over parentheses or `$`). Think this is reasonable. Solves #310.
GHCi can be a bit awkward about column numbering, according to whether a template haskell expression is parenthesised or not (parentheses seem to +1 everything, if the "thing at point" is a parenthesised single character, only a single column is provided, rather than start and end...). I think I have this covered sensibly in the regex that grabs the expansion.
Overview of changes
* Load intero backend with `-ddump-splices` and `-XTemplateHaskell`.
* Add function to expand template haskell at point. This works by making the intero backend load the buffer's temporary file, and then …
=> Template haskell expansion

elisp/intero.el
"Targets:" told me 0 when I used this function.
=> Make the multiswitch buffer intelligible

elisp/intero.el
Alternate fix would be to define an "intero-string-join" locally, or just use the classic `(mapconcat 'identity strings sep)`.
=> Require Emacs 24.4 rather than 24.3, due to use of string-join

elisp/intero.el
dbeea0c tried to make this change, but `add-hook` local parameter is the fourth
argument not the third.
=> * intero.el: Add intero linkify hook only locally

elisp/intero.el
```
There were multiple candidates for the Cabal entry "test.hs" (/home/mark/projects/betterteam/.stack-work/downloaded/Ua0N4hDm1zuC/yesod-core/test.hs), picking /home/mark/projects/betterteam/.stack-work/downloaded/Ua0N4hDm1zuC/yesod-core/test/test.hs
The following GHC options are incompatible with GHCi and have not been passed to it: -Werror -threaded
Configuring GHCi with the following packages: thoth
/usr/lib/ghc/settings: openFile: does not exist (No such file or directory)
---
This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.
TROUBLESHOOTING
It may be obvious if there is some text above this message
indicating a problem.
If you do not wish to use Intero for some projects, see
https://github.com/commercialhaskell/intero#whitelistingblacklist …
```
=> Intero is crashing for me at the moment, but that's another issue - this is about the error message i'm getting when it crashes.

elisp/intero.el
- `define-minor-mode` is a better way to declare the global minor mode, since it allows conventional toggling
- rename (but alias) the minor mode to consistently use the `intero-` prefix
Filing this as a pull request for review, rather than committing directly, though I think it's uncontroversial.
(Related: the conventional behaviour for a global minor mode like this would arguably be to enable `intero-mode` in all _pre-existing_ haskell buffers as well as future ones when enabled, and to disable it everywhere when disabled. Not sure whether that was considered in this case, or judged to be problematic/undesirable.)
=> More conventionally define (and name) the global mode

elisp/intero.el
Resolves #393.
Use cases:
* testing different versions of Stack side-by-side,
* substituting `stack` with a small shim that uses a different resolver, e.g. Nix.
=> Allow choosing which Stack executable to use

elisp/intero.el
I’m sorry I missed these in #394, please, see https://github.com/commercialhaskell/intero/pull/394#issuecomment-292129196.
=> Replace "stack" with intero-stack-executable in debug/help messages

elisp/intero.el
Resolves #401.
Every time `(with-temp-buffer)` is used, any local variables of the calling buffer are not propagated down.
One such variable is `intero-stack-executable`, which the user might want to change locally (potentially, using .dir-locals.el). Since processes are most often started in new, temporary, non-file-visiting buffers, these new buffers need to see the value requested by the user.
=> Fix propagation of buffer-local variables

README.md, elisp/intero.el
This changes `intero-global-mode` so that it honours `intero-whitelist` and `intero-blacklist`. This renders the `intero-mode-whitelist` and `intero-mode-blacklist` functions obsolete, and simplifies the set-up advice: users can simply customise the list vars and then enable the global mode.
Should be entirely safe to merge, but I'll hold off for a day or two to allow for any objections!
=> Make intero-global-mode handle white/black-listing

src/GhciFind.hs, src/GhciInfo.hs, src/GhciTypes.hs, src/test/Main.hs
This uses the existing import declarations from ModInfo. It also stores the location of the module in ModInfo. 
I'm not sure about handling of the locations as now there are three types of ranges (SrcSpan, SpanInfo and 4 Ints). 
It should implement #181.
Let me know what you think.
=> Make :loc-at work with module imports (implements #181)

elisp/intero.el
This introduces an Intero-specific help buffer instead of re-using the emacs lisp help buffer:
1. `C-c C-i` now works inside the help buffer, so you can drill down into data types.
2. `C-c C-t` will report the type in the minibuffer as usual, but also insert it into the help buffer in the background. So if you want to drill down into a type, you can switch to that buffer and continue with `C-c C-i`.
Great for exploring a new project.
=> New help buffer

elisp/intero.el
This makes it composable with other `eldoc-documentation-function` providers.
This snippet is used in other plugins:
https://github.com/leoliu/ggtags/blob/master/ggtags.el#L2246
https://github.com/abingham/emacs-ycmd/blob/master/ycmd-eldoc.el#L222
=> eldoc-documentation-function: change setq-local to add-function/remove-function

README.md, elisp/intero.el
Hi, first-time contributor here!
This commit adds the ability to switch yaml config files using `M-x intero-stack-yaml`. Intero still works as before by assuming the default stack.yaml / global file, but now you can change it afterwards. You can optionally preserve that change across sessions. Switching yaml files restarts intero and intero-repl. 
I would appreciate if anyone can look at my this commit and let me know if it's OK. 
I have not addressed #211, however I think this commit is a step towards that.
=> Add ability to specify stack yaml file to use (closes #105, #298)

elisp/intero.el
This is a change I had in haskell-mode for ages, and for some reason never bothered to add it to Intero. Finally I got sick of manually writing just that one extension so I added this.
It's enabled not by default, because sometimes you simply have a type error against String or [Char]. But when you just need OverloadedStrings enabled, it's great.
=> Add suggestion for OverloadedStrings

intero.cabal, src/test/Main.hs
Tests should run correctly on Windows now.
One of the solutions in particular relies on System.Info.os, as it turns out different outputs are generated depending on the OS. Other solutions for that include things like CPP, which I'm not sure are desirable at all.
=> Fix tests on Windows

stack.yaml
Appears this was missing as I couldn't compile the project without it.
Connected to this (and I don't actually know the answer), should stack.yaml be part of the tarball? I'm wondering because as a NixOS user when intero attempts to build itself it does it without honouring any of the nix options and then fails because there's no curses library available.
=> Added Clang to nix packages.

elisp/intero.el
We used to be able to quit the suggestion pane with `C-g`, but that
was removed in 397e5c8258c97be8e2abb1d34526219fc816ca86. The the `C-g`
was intuitive to me, but `C-c C-k` was not -- I had to look at the Git
log to figure it out -- so I thought it would be helpful to document
it. My next guess after `C-g` was `q`, which is also more intuitive
than `C-c C-k` to me.
I did not test this change, since I don't know how to run Emacs
packages from source.
=> Document that `C-c C-k` quits the suggestion pane

elisp/intero.el, intero.cabal, src/InteractiveUI.hs
@purcell The infamous flycheck disappearing error messages error persisted since we fixed it. At the time I was so busy I just accepted it. It's starting to become a problem for me. I ended up developing a habit of hitting RET just to make the flycheck errors update.
Are you not reproducing this? The elisp-side caching we did doesn't work. 
Meanwhile I've come up with an alternative solution:
The problem with the historical approach is that Emacs Lisp writes to the temp file NOW. For the duration of one second, any subsequent updates to the module are ignored by GHCi. And, of course, our code doesn't rewrite the file if the contents didn't change. So there's nothing to invalidate the file afterwards anyway. But even if we did update the file, it'd be ignored for 1 second. So we need a way …
=> Fix cache invalidation strawman

elisp/intero.el
Oh the joys of life without a type-checker!
Fixes #471
=> Remove old reference to intero-check-calculate-hash

elisp/intero.el
This pull request adds the option to disable `pop-to-buffer` when evaluating code either via `intero-repl-eval-region` or `intero-repl-load` (or any other function that uses `intero-with-repl-buffer`). This was done purely out of personal need as my other REPL environment (clojure / cider) doesn't pop up the repl buffer on evaluate :-) 
One could also implement a more sophisticated approach, either allowing full customization of what function is used for showing the buffer, or by allowing users to choose if they want to jump to the buffer based on some other predicate, for example the prefix-arg. 
This minimal approach is just a first step (and to probe if you're interested in this kind of improvements to `intero-mode`).
Cheers!
=> Add `defcustom` to disable `pop-to-repl` on `C-c C-l`.

elisp/intero.el
See https://github.com/commercialhaskell/intero/issues/476#issuecomment-348467874 for detailed explanation.
I'm going to spend the day on this branch; if it doesn't cause any regressions in behavior (or bad performance), I'll merge to master.
If you want to test this out now, just run `killall intero` and start the processes up again.
=> Enable -fdefer-type-errors on start-up

elisp/intero.el
I ran into trouble when exporting some Org files that had Haskell ~src~ blocks since I switched to white-listing.
=> Handle a null (buffer-file-name) when white/black listing

elisp/intero.el
This checks if the path of the current file is equal to the content of
"intero-repl-load". If the paths are equal, the file is only reloaded, which
skips recompilation of unchanged dependency modules.
This is faster and a bit more convenient in larger projects.
This would resolve enhancement request #474
=> #474 Only ":reload" file if it is equal to "intero-repl-last-loaded"

elisp/intero.el
Deferred executors will run in wrong buffer context.
=> Do not sleep-for in with-current-buffer

elisp/intero.el
Reverts commercialhaskell/intero#498
If the module isn't successfully loaded, ghci just says:
```
 Ok, modules loaded: none.
 Ok, modules loaded: none.
 Ok, modules loaded: none.
 Ok, modules loaded: none.
```
=> Revert "#474 Only ":reload" file if it is equal to "intero-repl-last-loaded""

elisp/intero.el
I would like propose a bunch of improvements, which can be roughly summarised as follows:
- Performance enhancements - emacs would do less work and would (hopefully) work faster. The only danger here is that when I changed `string-match` to `string-match-p` and `looking-at` to `looking-at-p` I may have missed a place where match data was subsequently accessed. But hopefully that didn't happen...
- Customisability enhancements - move more stuff (i.e. keymap for `intero-multiswitch`) to variables or add new variables (i.e. `intero-extra-ghc-options` and `indero-extra-ghci-options`) so that a user may influence intero's behaviour without having to change it's source code.
- New feature - completion in repl for `:set` command. Could probably be improved to complete other commands as well, but …
=> Primarily customisability enhancements

elisp/intero.el, intero.cabal, src/GhciMonad.hs, src/InteractiveUI.hs
* To the Intero executable: 
1. The ability for read-only commands (`:type-at`, `:loc-at`, `:complete-at`, `:uses-at`) to be **called in a separate thread** to the main thread, which may be compiling a module. List [here](https://github.com/commercialhaskell/intero/blob/76ba40109ada211d76bf435ea6cb8c16227d68d5/src/InteractiveUI.hs#L301..L308). 
2. A simple TCP service that listens on a _random available port_ on loopback (127.0.0.1-only), which is reported when it starts up as `Intero-Service-Port`.
* For the Emacs mode, 
1. We pick up the `Intero-Service-Port`  when starting the Intero process. 
2. We add two new functions `intero-async-network-call` and `intero-blocking-network-call` which both connect to the service. _One new connection per command request_, and after the response is …
=> Support asynchronous read-only commands

src/InteractiveUI.hs
Not all systems support the UseLoopBack socket option.
Network.Socket.setSocketOption throws an exception when a system doesn't
support the socket option. This commit checks if the system supports
`UseLoopBack` before attempting to set it.
Fixes https://github.com/commercialhaskell/intero/issues/518
=> Check if UseLoopBack socket option is supported

CHANGELOG, elisp/intero.el, intero.cabal, src/Completion.hs, src/GhciFind.hs, src/InteractiveUI.hs
As discussed in #524. In order to aid experimenting, I'm merging this into master once the CI checks come through.
This feature will only trigger if you type `_` and have company-mode enabled (which is intero default). Alternatively, if you run `M-x company-complete` (or other keybinding). I've rebound my `M-/` to dabbrev-expand unless on a `_` and then it runs `company-complete`.
=> Add :fill command

elisp/intero.el
Reverts commercialhaskell/intero#523
With the above change, I see a lot of:
```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
intero-network-call-sentinel(#<process backend> "deleted\n")
```
so it seems like this fix isn't the correct one.
/cc @sergv
=> Revert "Delete network buffers after use"

elisp/intero.el
- Quote all paths with ""
- Escape only \ and "
- Don't rely on %S elisp string escaping
- Remove special-case handling for :move
This allows all commands to safely handle Windows paths and both directory paths and filenames which contain spaces on any platform.
This should replace #541 if it is found to work for all concerned - I've tested this on a UNIX machine to my satisfaction.
=> Properly and consistently quote file paths for GHCi :commands

elisp/intero.el
stack already sets the `-odir` and `-hidir` to a place in `.stack-work` which is stable and cacheable.
Removing this makes intero much faster at restarting on large projects, because all the object files are cached.
Here is a sample intero debug log, two intero-restart invocations: https://gist.github.com/chrisdone/35d870f02180793b132646f637373fe0
That is, once PR #4038 lands:
https://github.com/commercialhaskell/stack/pull/4038
Until that lands the user won't notice a difference.
=> Remove -odir/-hidir, trust stack ghci to set them

elisp/intero.el
Since it's not clear from the docstrings how whitelist/blacklist
interact in intero-global-mode.
=> Let docstring mention non-obsolete usage of whitelist + need for /

elisp/intero.el
This can occur if GHC died with a segfault, for example.
=> Restart GHC in intero-repl-buffer if repl buffer already exists

elisp/intero.el
This fixes #570 . `and` blocks in elisp return the last "truthy" value, otherwise nil. #570 as a result returned the process and not the buffer when the `and` expression was true, resulting to an error described in #572 .
=> Return the buffer instead of the process when creating the repl buffer

.travis.yml
Our case with all possible combinations of resolver and OS and only one exclusion is quite an exemplary case for the build matrix, so this converts explicit jobs to implicit.
Also converts `ARGS` environment variable to `RESOLVER` since we're using only it anyway.
=> Travis: make use of build matrix

elisp/intero.el
The flycheck message for a suggestion is hardcoded to
"Hit `C-c C-r` in the Haskell buffer to apply suggestions"
But this may be misleading depending on the actual keybindings - e.g. in Spacemacs `C-c C-r` is bound to haskell-process-reload instead.
=> Substitute command keys for flycheck message

README.md
The `README.md` uses `libtinfo-dev` as a package name of `libtinfo` for GNU/Linux. While the name is valid for Debian-based distros, other distros put the library into a different package. 
- Explicitly mention `libtinfo-dev` as a package for Debian derivatives.
- Add package name that installs `libtinfo` on Fedora derivatives.
=> Add libtinfo installation instructions for Fedora derivatives

CHANGELOG, elisp/intero.el, intero.cabal, src/test/Main.hs, test/test-ghcs
Well, nothing much to say. The upgrade from 8.6.3 to 8.6.4 is pretty much about the change in the upperbound.
=> Bump GHC upper bound to 8.6.4

elisp/intero.el
After updating `stack` and `intero` to the latest versions, I wasn't able to run a repl inside spacemacs anymore because I'd get the following error:
```
Invalid option `--tty=false'
Usage: stack ghci [TARGET/FILE] [--pedantic] [--ghci-options OPTIONS]
[--ghc-options OPTIONS] [--flag PACKAGE:[-]FLAG]
[--with-ghc GHC] [--[no-]load] [--package ARG]
[--main-is TARGET] [--load-local-deps] [--[no-]package-hiding]
[--only-main] [--trace] [--profile] [--no-strip] [--[no-]test]
[--[no-]bench] [--help]
Run ghci in the context of package(s) (experimental)
---
This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.
TROUBLESHOOTING
It may be obvious if there is some text above this message
indicating a problem.
If you do not wish to use Intero for some projects, …
```
=> Remove broken exec arg --tty=false

TOOLING.md
* "https://github.com/commercialhaskell/intero.git" -> "https://github.com/chrisdone/intero.git"
* Remove spaces which seem unnecessary.
=> Fix a deadlink in TOOLING.md

elisp/intero.el, src/GhciInfo.hs
This should fix #627.
A couple of points/questions:
* Does this mean that other editor integrations now need to follow the switching logic, on pain of intero not correctly tracking when files have been loaded?
* I've checked that the elisp compiles, but I'm afraid I'm too much of an emacs noob to test this locally. I tried `M-x install-file` but got errors when intero tried to install itself. Sorry about that.
> Before this commit, we pass `-fobject-code` to ghci, which produces
> build artifacts (object files). This allows subsequent reloads to be
> faster and improves the performance of intero.
> 
> It is possible to output interface files while only doing the work of
> typechecking with the flags `fno-code` and `fwrite-interface`. This,
> again, improves the performance of intero.
> 
> …
=> Use `fno-code fwrite-interface` when GHC >= 8.4.1
