.gitignore
ghc/GhciFind.hs
ghc/GhciInfo.hs
ghc/GhciMonad.hs
ghc/InteractiveUI.hs
ghc/Main.hs
ghci-ng.cabal

This compiles but I'm not sure if it's "optimal".

Ghc7.10 - fixes #15

---

src/InteractiveUI.hs

reapply 7309426 (configurable completion) which was removed in 9bef3b3

---

elisp/intero.el

Decided to attack all the flycheck errors and warnings for intero. Probably further fixes on their way!

Make all docstrings compliant with checkdoc

---

elisp/intero.el

I imagine there are a lot of suggestions to come on line, and things could get long and messy.
Happy to help with a refactor if anyone has a sense of how to handle these cases.

add suggestions for turning off name shadowing and default warnings.

---

elisp/intero.el

This one is a bit involved on the parsing side.

Apply GHC's suggestions on redundant constraints

---

elisp/intero.el

Implements clear buffer support in the repl.

---

elisp/intero.el

This reproduces haskell-mode's handy toggle switching and its familiar keystrokes: when switching to the intero REPL with the new C-c C-z binding, the previous buffer is noted, and then C-c C-z in the intero REPL switches back to that buffer.
The implementation here is perhaps slightly clunky, in that it adds to `intero-repl-buffer` the responsibility for optionally noting the original buffer. The alternative would be to leave that function unchanged and provide an `intero-repl-switch` wrapping function or similar. Let me know if you'd prefer this, and I'd be happy to rework the PR slightly.

Use C-c C-z to switch to and from REPLs

---

elisp/intero.el

Improves the linkification logic.

---

elisp/intero.el

This is an initial solution to #242, wherein `intero`'s magical silent saving of buffers was causing all sorts of problems.
The implementation here uses a buffer-local variable to track an associated temp file, the contents of which will be kept up-to-date with the buffer contents. Intero backend calls are then made against that buffer, and the flycheck results translated back accordingly.
With these changes, all save-related behaviour (including before/after save hooks) works as expected.
AFAICT this all works fine. The implementation is slightly inefficient, in that it will sometimes lead to the buffer being redundantly re-written to the temp file, but it's fast and straightforward to understand. If you'd prefer, I'd be happy to work on streamlining it.

Write buffer to a temp file rather than silently forcing save

---

elisp/intero.el

also keep around a cache to make eldoc messages show immediately where
possible, but always make a request and update the cache since we want
the Right answer as soon as we can have it without adding any
invalid-cache-complications

do eldoc asynchronously (fix #265)

---

intero.cabal
src/GhciFind.hs

Support completion of qualified identifiers

---

elisp/intero.el

This allows all temp files to be seen by the stack commands, even when stack's docker support is enabled. See #279, #293.

Consistently use .stack-work/intero for temp files

---

elisp/intero.el

I've been working on making intero work over TRAMP, and this is a possible first chunk of work in that direction. Editing over TRAMP is a regular use case for me, and I discovered intero a few days ago - it looks good! Partial resolution of #303 . Local intero works as before (to the best of my knowledge). Over TRAMP, intero with these changes will
* Install intero in the stack environment (if needed)
* Run an intero background process
* Load files into an intero REPL (including loading the "prompt change script")
* Perform goto-definition
* Do type at point
company and flycheck integrations don't appear to work at the moment (next things on my list), and everything else goes as untested (and largely unmodified). I thought it best to get feedback on the work so far, for …

Made basic features work over TRAMP

---

elisp/intero.el

Made flycheck work over TRAMP. Tidied a couple of other odds and ends from previous TRAMP work.
Key work in `intero-parse-errors-warning-splices`. `flycheck` wasn't correctly identifying the buffer to display errors in, because it was comparing a local and remote path (with `string=`). I made the paths remote (when remote), and wrote a comparison function for paths to replace `string=`, since TRAMP paths have a few variations.
Furthers solving #303. Builds on #340.
Commit notes
===========
The background process was finding errors, but the flycheck backend was not identifying the buffer to display errors in. This was because it was comparing the absolute path from the buffer, and the local path from the background process. Fixed this, and provided a general utility function for comparing …

Made flycheck work over TRAMP

---

elisp/intero.el

intero.el: Pass -ignore-dot-ghci to intero except for intero-repl

---

elisp/intero.el

See @purcell’s comment here: https://github.com/commercialhaskell/intero/pull/394#issuecomment-292081836.

Don’t make intero-repl-no-load and intero-repl-no-build buffer-local

---

intero.cabal

Add -fPIC to cc-options

---

elisp/intero.el

This addresses #143, wherein flycheck warnings were getting lost after two flycheck passes in quick succession since the second underlying :l command simply said "ok".
The approach taken here is to note the temp buffer modification time and results for a flycheck pass, and then to simply replay them if another pass is requested with the same temp buffer mod time.
In order to make this work, we have to ensure that the mod time of the temp buffer is not updated unless its contents change, which introduces a small inefficiency: the temp file is now first quickly read before conditionally writing to it.

Cache flycheck results when the source is unchanged

---

elisp/intero.el

This functionality is borrowed from  the code I wrote for haskell-mode.
This works great for me, super useful for refactoring names and highlighting uses. As-implemented has worked for me for a long time. But the keybindings might conflict with people's expectations.
@purcell Do you recommend some more appropriate keybindings?
I once tried integrating this with multiple-cursor-mode but generally I have trouble with that minor mode (sadly).

Implement find-uses (display and rename)

---

elisp/intero.el

GHC 8 suggests identifiers that you could add to an explicit import list. This adds support for it in the suggestions system.
Arguably this makes maintaining explicit import lists much more practical. An accompanying PR to remove unused explicit imports would be handy too.

Add to import lists suggestions by GHC

---

elisp/intero.el

This adds support to the suggestions system for removing symbols that GHC reports as redundant from import lines.

Remove redundant imported symbols

---

cbits/hschooks.c
intero.cabal
src/GhciFind.hs
src/GhciMonad.hs
src/InteractiveUI.hs
src/Main.hs

Changes to work with GHC 8.2.1-rc1 API

---

elisp/intero.el

I noticed that a new network buffer is created for each 'read-only' command like get type of thing at point. After a while a lot of such buffers is created but they are never cleaned up.

Delete network buffers after use

---

elisp/intero.el

Add missing field suggestions

---

elisp/intero.el

I created the function  `intero-repl-completion-at-point`, an alternative company function. This should provide a native ghci auto-complete experience in the intero repl when paired with the changes from https://github.com/commercialhaskell/intero/commit/f80d503fd682defc750406ef3021091b732edffe. 
Here's a small demo of a user experience before and after. `After` includes the `notInExport` in completions and fixes issue https://github.com/commercialhaskell/intero/issues/529

ghci-like repl autocomplete

---

elisp/intero.el

See #544. Unfortunately I seem to have the worst of both worlds. With
2c2546b I get "selecting deleted buffer" errors, sometimes causing emacs
to hang briefly; and with 37af015 my buffer list continues to grow,
though maybe slower than before. (I'm using emacs 25.1.1.)
It appears that for me, the "deleted\n" event is only getting triggered
inconsistently when `(delete-process)` is called. So I return to killing
the buffer immediately. But I also handle the deleted event to avoid
errors.
I considered having
(when (buffer-live-p (process-buffer process))
(kill-buffer (process-buffer process)))
inside the deleted event, as a fallback. But it doesn't seem to get
called for me in normal workflow, so if something unusual is happening,
I decided to not destroy the evidence of it.

More robustly delete network process buffers.

---

elisp/intero.el

Fix for https://github.com/commercialhaskell/intero/issues/553

Fix restoring intero-targets from .dir-locals.el

---

intero.cabal

Allow building with GHC-8.4.4

---

.travis.yml
appveyor.yml

Stackage LTS 12 is released for quite a while, let's pick it up.

CI: nightly -> LTS 12 

---

.travis.yml

cache `$HOME/.stack` dir (hopefully) improving consecutive build times

Travis: cache .stack dir

---

.travis.yml

Builds against nightly do not trigger build failure though.

travis: add nightly Stackage, reorder resolvers

---

.travis.yml
appveyor.yml
src/GhciFind.hs
src/test/Main.hs
test/test-ghcs

Ignore deferred scope names

---

intero.cabal
src/test/Main.hs
test/test-ghcs

Following up the GHC upgrade in stackage LTS-13.20

Bump GHC upper bound to 8.6.5

---

elisp/intero.el

Bump intero package version in intero.el

---

README.md

Arch Linux package for `libtinfo`

Add Arch Linux requirement

---

README.md

Added Howl-Intero to README

---

README.md

The intero project has reached the end of its life cycle. 🌇 
* I will not be maintaining it any longer.
* Minimal pull requests will be accepted for a few months.
* After which, I will archive the project.
If an individual or group would like to fork take over the project, they are welcome to do so. I will update this README to point to those alternatives.
Alternatives:
* [Dante](https://github.com/jyp/dante)
* [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine)

Sunsetting intero

---

README.md

Thanks for your awesome work on Intero. Some of Ghcide was bootstrapped by taking Intero code, so we greatly appreciate it. Perhaps list Ghcide as a possible alternative? (In future times it may merge with HIE, but that's probably a way off, and not a guarantee)

Add Ghcide as a possible alternative
